### PR TITLE
Add publishNotReadyAddresses to headless service to fix clustering on restart

### PR DESCRIPTION
**Pull request by Ghkuijer**
Fix for #265.

We have noticed the issue as well. We tried this solution on our cluster and after forcing a restart on all pods at the same time the pods now cluster correctly within a couple of seconds.

### CODE REVIEW

**Comment by ioolkos** [comment]
@Ghkuijer Thanks a lot! Can you please delete the binary file from the PR? (`.tgz`).
Is this a fix for the latest release, that is tested with `1.13.0`?

**Comment by Ghkuijer** [comment]
@ioolkos removed the binary file. I have tested this with with the charts from the master branch in the repo so yes I expect that that is the exact same version as 1.13.0. We run on 1.13.0 as well on our production cluster as we use the published charts on the Vernemq helm repo there.

**Comment by Ghkuijer** [comment]
@ioolkos any chance you have some time to look this PR over and that we can publish it after merge?

**Comment by ioolkos** [comment]
@Ghkuijer  my concern was exactly as described here: https://github.com/kubernetes/kubernetes/issues/118952
But since this change is only for the headless service, I think we can do this. That node will then accept traffic right away, let's see whether this causes issues.

BTW, do you use self-built Docker images? (Note that the EULA-based packages require a paid subscription for production use)

**Comment by ioolkos** [comment]
Ah, we had also merged this PR, for retrying cluster joins. This looks like an attempt to solve the same problem (or maybe partially). 
https://github.com/vernemq/docker-vernemq/pull/363

**Comment by Ghkuijer** [comment]
> Ah, we had also merged this PR, for retrying cluster joins. This looks like an attempt to solve the same problem (or maybe partially). #363

If that change was already published then we are already using that fix and it doesn't solve the problem completely yet without the fix from this PR. With this fix it will solve the problem completely.

Do you maybe have a reference for me about the paid subscriptions and when Vernemq can still be used free of charge? I have been looking all over and until now all I could find were open source licensed free of use.

**Comment by Ghkuijer** [comment]
> BTW, do you use self-built Docker images? (Note that the EULA-based packages require a paid subscription for production use)

Actually found the info on payment. Its not a thing you have to actively accept so missed it in our efforts. We will switch to own build images ASAP.

**Comment by ioolkos** [comment]
@Ghkuijer you have to actively accept the EULA, this is not pre-configured.

Please consider supporting the open-source solutions you are commercially using. Sponsoring is another option.

**Comment by Ghkuijer** [comment]
> @Ghkuijer you have to actively accept the EULA, this is not pre-configured.
> 
> Please consider supporting the open-source solutions you are commercially using. Sponsoring is another option.

Then I think that is another bug since our Vernemq cluster using the Helm chart just runs without actively accepting that EULA. We will definitely consider supporting Open Source projects we are using but as we are a pretty small company we have to do so in ways that we can. I try to help out personally by contributing with fixes to bugs that we come across instead of only reporting them.

**Comment by ioolkos** [comment]
@Ghkuijer appreciate it! :)
(will have to check what the Helm chart does)

**Comment by ioolkos** [comment]
cherry-picked dbe19b1e4d247b189f90515635eba47fb2f9ecb2. Thanks again @Ghkuijer

**Pull request closed without merging**
