### PR TITLE
Add support for updating erlang VM args through environment variable, use short form flags for max_ports and max_ets_tables

### LINKED ISSUE #306: Values set for erlang VM arguments using env variable is not considered
I've set the Erlang process limit using the following environment variable

`DOCKER_VERNEMQ_ERLANG__PROCESS_LIMIT: "512000"` while vernemq/vernemq:1.12.3 image.

When I checked the running process inside the container, the value for "+P" is set as 25600.

`/vernemq/bin/../erts-11.2.1/bin/beam.smp -P 256000 -A 64 -K true -W w -zdbbl 32768 -- -root /vernemq/bin/.. -progname vernemq -- -home /vernemq -- -boot /vernemq/bin/../releases/1.12.3/vernemq -config /vernemq/data/generated.configs/app.2021.12.06.11.07.56.config -setcookie vmq -name VerneMQ@172.25.0.2 -smp enable -- -vm_args /vernemq/bin/../etc/vm.args -pa /vernemq/bin/../lib/erlio-patches -- console -noshell -noshell -noinput --`

The updated value is shown under vm.args file in generated config, but there is a vm.args file under /vernemq/etc/ directory and it doesn't have the updated value.

As per documentation, having vm.args file in the same directory of vernemq.conf will override any Erlang specific parameters your might have configured via the vernemq.conf.

### PR DESCRIPTION
**Pull request by iam-nagarajan**
Fixes #306

### CODE REVIEW

**Comment by ioolkos** [comment]
@iam-nagarajan Yep, this totally makes sense & fixes and overlook. Thanks!

**Review by ioolkos — APPROVED** [review]

**Comment by ioolkos** [comment]
@iam-nagarajan 
Can you please use the short forms of flags in the `vm.args` file:

`+Q` instead of `-env ERL_MAX_PORTS`
`+e` instead of `-env ERL_MAX_ETS_TABLES`

While we're at it, we might also want to add 
`+zdbbl` with the value set in `erlang.distribution_buffer_size`

**Comment by iam-nagarajan** [comment]
@ioolkos Added a change to use short form flags and also added env variable for zdbbl

**Comment by iam-nagarajan** [comment]
@ioolkos can you please review this?

**Review by ioolkos — APPROVED** [review]

**Pull request merged**
