### PR TITLE
Add wss to statefulset definition rather than bin script

### PR DESCRIPTION
**Pull request by ioolkos**

### CODE REVIEW

**Review by cedricve — COMMENTED** [review]
looks better!

**Comment by cedricve** [comment]
looks good, just wondering if you undo the changed in the .sh file?

**Comment by cedricve** [comment]
Just tried it out with latest image, and looks like this is again no longer working. I remember it work with the previous PR. https://github.com/vernemq/docker-vernemq/pull/258

Can you also check @ioolkos ?

**Comment by cedricve** [comment]
It looks like the wss is not added by this fix:

accept_eula=yes
listener.ssl.default=10.24.6.13:8883
listener.ssl.keyfile=/etc/ssl/vernemq/tls.key
allow_subscribe_during_netsplit=on
listener.wss.certfile=/etc/ssl/vernemq/tls.crt
listener.ssl.certfile=/etc/ssl/vernemq/tls.crt
allow_publish_during_netsplit=on
allow_anonymous=on
listener.ssl.cafile=/etc/ssl/vernemq/tls.crt
allow_unsubscribe_during_netsplit=on
listener.wss.cafile=/etc/ssl/vernemq/tls.crt
listener.wss.keyfile=/etc/ssl/vernemq/tls.key
log.console=console
allow_register_during_netsplit=on
listener.tcp.localhost=127.0.0.1:1883
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 10.24.6.13:1883
listener.ws.default = 10.24.6.13:8080
listener.vmq.clustering = 10.24.6.13:44053
listener.http.metrics = 10.24.6.13:8888

**Comment by ioolkos** [comment]
@cedricve hm, can only test later, but have you enabled the service in the `values.yaml` file?

**Comment by cedricve** [comment]
Yes did like before.. 

Kind regards,
Verstraeten Cédric

**Comment by cedricve** [comment]
So just for completeness, pulling `latest-alpine`

I confirm this is set.

    wss:
      enabled: true
      port: 8443
      # This is the port used by nodes to expose the service
      nodePort: 8443

When creating vernemq with the helm chart. Despite of having this stateful set.

    {{- if .Values.service.wss.enabled }}
        - name: DOCKER_VERNEMQ_LISTENER__WSS__DEFAULT
        value: "$(MY_POD_IP):{{ .Values.service.wss.port }}"
    {{- end }}

The environment variable is not set in the vernemq container. 
~ $ echo $DOCKER_VERNEMQ_LISTENER__WSS__DEFAULT

And thus it is not being created in the /vernemq/etc/vernmq.conf

**Comment by cedricve** [comment]
I confirm I did, `helm update`as well, and see below output when doing a describe of the pod.

      $ kubectl describe po vernemq-0 
      Name:         vernemq-0
      Namespace:    default
      Priority:     0
      Node:         gke-kerberos-test-pool-2-3bae2e38-zsq9/10.132.0.17
      Start Time:   Fri, 20 Nov 2020 18:45:27 +0100
      Labels:       app.kubernetes.io/instance=vernemq
                    app.kubernetes.io/name=vernemq
                    controller-revision-hash=vernemq-666b86b95f
                    statefulset.kubernetes.io/pod-name=vernemq-0
      Annotations:  kubernetes.io/limit-ranger: LimitRanger plugin set: cpu request for container vernemq
      Status:       Running
      IP:           10.24.3.10
      IPs:
        IP:           10.24.3.10
      Controlled By:  StatefulSet/vernemq
      Containers:
        vernemq:
          Container ID:   docker://596b5d4927aad9eb71ed6b20c3d44e95307e4e23b837cf1256e6204a6f32568d
          Image:          vernemq/vernemq:latest-alpine
          Image ID:       docker-pullable://vernemq/vernemq@sha256:4dfde5f85d93119dd0aaf2fe750b136f0ca17661348f108820a7732d753cf141
          Ports:          1883/TCP, 8883/TCP, 4369/TCP, 44053/TCP, 8080/TCP, 8443/TCP, 8888/TCP, 9100/TCP, 9101/TCP, 9102/TCP, 9103/TCP, 9104/TCP, 9105/TCP, 9106/TCP, 9107/TCP, 9108/TCP, 9109/TCP
          Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
          State:          Running
            Started:      Fri, 20 Nov 2020 18:45:28 +0100
          Ready:          True
          Restart Count:  0
          Requests:
            cpu:      100m
          Liveness:   http-get http://:prometheus/health delay=90s timeout=5s period=10s #success=1 #failure=3
          Readiness:  http-get http://:prometheus/health delay=90s timeout=5s period=10s #success=1 #failure=3
          Environment:
            MY_POD_NAME:                                       vernemq-0 (v1:metadata.name)
            MY_POD_IP:                                          (v1:status.podIP)
            DOCKER_VERNEMQ_DISCOVERY_KUBERNETES:               1
            DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR:          app.kubernetes.io/name=vernemq,app.kubernetes.io/instance=vernemq
            DOCKER_VERNEMQ_LISTENER__TCP__LOCALHOST:           127.0.0.1:1883
            DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT:             $(MY_POD_IP):8883
            DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT:     on
            DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT:      on
            DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT:    on
            DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT:  on
            DOCKER_VERNEMQ_ACCEPT_EULA:                        yes
            DOCKER_VERNEMQ_ALLOW_ANONYMOUS:                    on
            DOCKER_VERNEMQ_LISTENER__SSL__CAFILE:              /etc/ssl/vernemq/tls.crt
            DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE:            /etc/ssl/vernemq/tls.crt
            DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE:             /etc/ssl/vernemq/tls.key
            DOCKER_VERNEMQ_LISTENER__WSS__CAFILE:              /etc/ssl/vernemq/tls.crt
            DOCKER_VERNEMQ_LISTENER__WSS__CERTFILE:            /etc/ssl/vernemq/tls.crt
            DOCKER_VERNEMQ_LISTENER__WSS__KEYFILE:             /etc/ssl/vernemq/tls.key
          Mounts:
            /etc/ssl/vernemq from vernemq-certificates (ro)
            /var/run/secrets/kubernetes.io/serviceaccount from vernemq-token-rkx87 (ro)
            /vernemq/data from data (rw)
            /vernemq/log from logs (rw)
      Conditions:


You will see the Environment Variable missing.

**Comment by cedricve** [comment]
@ioolkos ok looks like this new Chart version isn't pushed already? So it doesn't uses the latest statefulset.

**Pull request merged**
