### PR TITLE
Added env API_KEY to add api key at runtime

### PR DESCRIPTION
**Pull request by dvdred**
Can be used in docker-compose.yml:
`...
   environment: 
      - API_KEY=MyApiKey
`

### CODE REVIEW

**Comment by ioolkos** [comment]
@dvdred thanks... can you explain why this is needed? is it a backward compatible addition?
(if yes, I'll merge this)

**Comment by dvdred** [comment]
hello, sorry for the delay! the change was useful to me because I am using vernemq on docker swarm and I need to set an api key at runtime taking it's value froma a docker env. I have not found any other way.

**Comment by JesseLabruyere** [comment]
I'm also looking for this feature. Right now my startup script has to wait for the nodes to be reachable. Then I can try to add the key using the vmq-admin command. I have trouble getting this to work flawlessly 100% of the time. Being able to set the key using a environment variable would be awesome!

**Comment by SebUndefined** [comment]
You can do it by creating your own image derived from vernemq and override the CMD directive

`COPY commands.sh /scripts/commands.sh
RUN ["chmod", "+x", "/scripts/commands.sh"]
ENTRYPOINT ["/scripts/commands.sh"]
`

then you can start VerneMQ and start a command for building a key

`
#!/bin/bash
echo "Starting App and VerneMQ"
echo "Starting Hub in dev"
echo "##############################################"
echo "$API_KEY"
start_vernemq & 
/bin/sh -c "sleep 30 ; vmq-admin api-key add key=$API_KEY"
fg %1
`
`$API_KEY` is an env var. Just add it to your compose file.

**Comment by Ashtonian** [comment]
Can this be added to standard env keys?

**Comment by ioolkos** [comment]
> Can this be added to standard env keys?

@Ashtonian could be done, yes. by adding a mapping to the `vmq_server` schema file. (and some additional handling at boot time to add the API key to a config table as well)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
Closing, as we merged https://github.com/vernemq/docker-vernemq/pull/369.
Thank you again to everyone who helped out here!

**Pull request closed without merging**
