### PR TITLE
Fix helm init in ci

### PR DESCRIPTION
**Pull request by ofirshtrull**
stable helm repo  has moved to a new URL according to https://helm.sh/blog/new-location-stable-incubator-charts/

here I have fixed the helm init  command in the ci

### CODE REVIEW

**Comment by ofirshtrull** [comment]
?

**Comment by ioolkos** [comment]
Helm charts are on the Github gh-pages branch here, not helm.sh

**Comment by ofirshtrull** [comment]
I didn't touch helm.sh
I fixed the error I saw in the .travise-ci
from what I see it is the one in charge of helm deploy to the repo

**Comment by ioolkos** [comment]
okay, sorry, need to check on this then

**Comment by ofirshtrull** [comment]
https://github.com/vernemq/docker-vernemq/runs/1621472878

**Comment by ofirshtrull** [comment]
@ioolkos any update?

**Comment by ioolkos** [comment]
@ofirshtrull can you revert the reference to `helm.sh` which Verne currently does not use anyway. (maybe we should)
Then I can merge the PR.

**Comment by ofirshtrull** [comment]
but it is needed since the stable repo is deprecated
please see https://stackoverflow.com/a/65408163/6285019

**Comment by ioolkos** [comment]
@ofirshtrull Hm, okay, I'll add it, it can't do any damage. Thanks!

**Pull request merged**
