### PR TITLE
Add Helm chart

### LINKED ISSUE #82: VerneMQ Helm chart
It would be really nice to have an "official" [Helm](https://helm.sh/) chart to deploy VerneMQ on a Kubernetes cluster. It would avoid the issues like #79. I'me pretty sure the VerneMQ dev team already have templates of Kuberntes configurations.

Best would be to have it into the [official Helm chart repository](https://github.com/helm/charts).

### PR DESCRIPTION
**Pull request by francois-travais**
Here is the Helm chart I'm using at the moment. This PR fixes #82 and #90 and is based on my other PR #91.

This chart is missing the SSL for sure and I'm sure there are other features missing.

### CODE REVIEW

**Comment by dergraf** [comment]
@francois-travais Thank you very much for your contribution. 
As we're no Kubernetes experts (yet) and don't know the internals of Helm, I don't think we're able to maintain your Helm chart, so we need your support for this. 
Do you have the resources to (help us) maintain the helm chart?

**Comment by a7i** [comment]
@francois-travais Thank you for putting this together. I was facing some issues deploying this to AWS EKS and after spending some time, I realized that if I am using a custom namespace, the following environment var must be added.

```
            - name: DOCKER_VERNEMQ_KUBERNETES_NAMESPACE
              value: "{{ .Release.Namespace }}"
```

Would you consider adding the block above?

**Comment by francois-travais** [comment]
@a7i That's rather surprising, I thought I fixed this a while ago (https://github.com/vernemq/docker-vernemq/issues/70). 

The entrypoint script is suppose to look for the namespace in `/var/run/secrets/kubernetes.io/serviceaccount/namespace`, see [here](https://github.com/vernemq/docker-vernemq/blob/bea60e3af15c2118e4cc27e498fcee50cd6cffd4/bin/vernemq.sh#L27). Do you have this file in your pod? According to the [official documentation](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/), you should. But there may be a bug somewhere else then. I'm not using the default namespace and everything works for me.

In the meantime you can add your snippet in the `additionalEnv` in values.yaml.

**Comment by francois-travais** [comment]
@dergraf Right now, on my current mission I'm using VerneMQ on k8s with Helm so I can afford spending a little bit of time on this.

**Comment by dergraf** [comment]
@codeaddict, @drf opinions?

**Comment by JohnCMcDonough** [comment]
I'm running into a few different issues with this helm chart. 

1. The first one is caused by a bug in the latest version of VerneMQ's 1.6.2 image (or at least it seems like it). It's unable to lookup the service that the pod is running with, and so it treats the hostname as `vernemq-helm-0..vernemq-helm.svc.cluster.local`. I've put in a comment here: https://github.com/vernemq/docker-vernemq/issues/79 but I haven't heard back. I think that may be what's causing @a7i's issue. Downgrading to 1.6.1 fixes it. 

2. The second issue is that the DNS names of the pods are wrong. At least on the version of kubernetes I'm running, 1.10.1. Based on the docs, it should be `<vernemq.fullname>.<vernemq.fullname>-headless.<namespace>.svc.cluster.local` https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id. I'm getting `<vernemq.fullname>-<instance>.<namespace>.svc.cluster.local` If I ping that, it fails to resolve. If I ping `<vernemq.fullname>-<instance>.<vernemq.fullname>-headless.<namespace>.svc.cluster.local`, it resolves and pings correctly.

3. I also don't believe that the pods get DNS entries for a service until after the readiness checks pass. The vernemq ping (I think) has to hit the cluster DNS provider in order to hit it's locally running service. I've disabled the readiness and the liveliness checks during testing. 

    ```
    $ kubectl get endpoints # with readiness check
    NAME                    ENDPOINTS   AGE
    vernemq-helm                        34s
    vernemq-helm-headless               34s
    ```
    ```
    $ kubectl get endpoints # without readiness check
    NAME                    ENDPOINTS                                            AGE
    vernemq-helm            10.42.0.133:1883,10.42.1.198:1883,10.42.2.125:1883   2m
    vernemq-helm-headless   10.42.0.133:4369,10.42.1.198:4369,10.42.2.125:4369   2m
    ```

4. To maintain compatibility with older versions of Verne, we probably need to change the liveliness/readiness checks from using the full path of vernemq, to letting it lookup the binary from the path. In 1.6.1, vernemq is at `/usr/sbin/vernemq` in 1.6.2, it's at `/vernemq/bin/vernemq`.

I'm not sure why I'm running into some of these issues. What versions of Kubernetes are you running? Any insight you can provide would be greatly appreciated. I'll add more information as I get it.

**Comment by JohnCMcDonough** [comment]
Ah, the issue with the 1.6.2 Kubernetes discovery is: 
```
/usr/sbin/start_vernemq: line 28: jq: command not found
/usr/sbin/start_vernemq: line 28: curl: command not found
/usr/sbin/start_vernemq: line 29: [: ==: unary operator expected
/usr/sbin/start_vernemq: line 37: jq: command not found
/usr/sbin/start_vernemq: line 37: curl: command not found
``` 
https://github.com/vernemq/docker-vernemq/blob/bea60e3af15c2118e4cc27e498fcee50cd6cffd4/bin/vernemq.sh#L29

Those tools (curl and jq) must have been removed from the container.

**Comment by francois-travais** [comment]
@JohnCMcDonough Your issue as been described here https://github.com/vernemq/docker-vernemq/issues/90 and fixed by there https://github.com/vernemq/docker-vernemq/pull/91. You should build your own docker image based on the branch of either this PR or https://github.com/vernemq/docker-vernemq/pull/91.

**Comment by dergraf** [comment]
Merging this PR. Thank you @francois-travais for your efforts!
@JohnCMcDonough let's open another issue that addresses the bugs you're seeing.

**Comment by JohnCMcDonough** [comment]
Yeah, there may be no need to add issues. I switched to using the latest tag, and all of my issues went away. I looked more into it, and they were all symptoms of the docker image. 
The chart works great! Nice job @francois-travais!

**Comment by dergraf** [comment]
A great thank you from the VerneMQ team too @francois-travais .. let me know to which address I can send you some stickers, if interested ;)

**Pull request merged**
