### PR TITLE
[helm] Use tag latest to get the chart working out-of-the-box

### PR DESCRIPTION
**Pull request by francois-travais**
Fixes a problem spotted in #79

### CODE REVIEW

**Comment by dergraf** [comment]
@francois-travais from my limited Docker experience I figured out that using `latest` is a double-edged sword. As you know Helm much better than myself, do you know if this is common with Helm, or maybe a better solution would exist that requires a bit of engineering?

**Comment by francois-travais** [comment]
@dergraf I agree this isn't ideal, but right now the chart doesn't work without latest. The best way would be to push a new tag for every merge to master and update the chart accordingly. I suggest we start versioning the docker image, not just the erlang bit.

**Comment by dergraf** [comment]
Good point. Let's merge this and have the versioning discussion over at Slack.
Can you rebase your PR?
Do you know a good way to automatically test a Helm chart that we could integrate in the Travis CI?

**Comment by JohnCMcDonough** [comment]
You can also reference a specific hash, if we want to lock it to a specific version. Just snapshot the current latest, `docker images --digests` and use the `<image>@sha256:<sha>`. At least then it’s locked to a known working version.

**Pull request merged**
