### PR TITLE
add a healthcheck

### PR DESCRIPTION
**Pull request by chrisns**

### CODE REVIEW

**Comment by larshesel** [comment]
Hi, sorry we never got back to you on this.  Is this still something you'd like to have included?

**Comment by larshesel** [comment]
hi @chrisns ok, sorry to hear that. What were the reasons for moving on, if I may ask?

**Comment by chrisns** [comment]
Running in a docker swarm cluster for hardware resilience, and split brain on vernemq hurt me a few times.
Ended up opting for aws iot as a managed mqtt will implement greengrass when it becomes available in my region which will give me an on-site presence

**Comment by francois-travais** [comment]
Adding a healthcheck in the Dockerfile shouldn't conflict with liveness and readiness probes for a Kubernetes deployment: https://stackoverflow.com/questions/41475088/when-to-use-docker-healthcheck-vs-livenessprobe-readinessprobe

**Comment by dergraf** [comment]
merged.

**Comment by dergraf** [comment]
Follow up PR https://github.com/vernemq/docker-vernemq/pull/94

**Pull request closed without merging**
