### PR TITLE
Add wss to verne script

### PR DESCRIPTION
**Pull request by ioolkos**

### CODE REVIEW

**Review by cedricve — APPROVED** [review]
looks good

**Comment by cedricve** [comment]
@ioolkos  could someone approve this? would love to verify if it's fixed..

**Comment by cedricve** [comment]
cool @ioolkos, we first have to create a new release I guesss?

**Comment by ioolkos** [comment]
@cedricve you can use latest. latest-alpine is already up on docker hub, latest will build in a minute or so.

**Comment by PSanetra** [comment]
@ioolkos I am not sure about this new behavior. Does it make sense to create that listener if that endpoint is not necessarily secured by a certificate? I guess it would be more consistent if that environment variable is set in the Helm chart if `.Values.service.wss.enabled` is set. Similar to the way how this case is handled for `DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT`: https://github.com/vernemq/docker-vernemq/blob/master/helm/vernemq/templates/statefulset.yaml#L78

**Comment by ioolkos** [comment]
@PSanetra ah, you're right. So the missing piece is actually in `statefulset.yaml` where we need to add a similar if-clause like for SSL.
@cedricve: I'll revert the add to the bin script, see above, it doesn't make much sense due to potentially missing certs configs.

**Comment by cedricve** [comment]
yes correct @ioolkos, makes a lot more sense because now it's enabled by default, which might not be the expected behaviour for someone else.

**Pull request merged**
