### PR TITLE
Add Helm value to specify the image pull secrets for the Pod

### PR DESCRIPTION
**Pull request by nicovanlooy**
Make it possible to pull the Docker image from a private registry.

### CODE REVIEW

**Comment by alan-copeland-keysight** [comment]
@ioolkos - ran into a new use-case for this one: DockerHub has begun more aggressively rate limiting image pulls from docker.io. We're running into problems pulling images unless we pass imagePullSecrets, even for publicly accessible images like Postgres. I imagine even your paying customers will soon run into this issue and need to set imagePullSecrets

**Comment by zollinger** [comment]
I'm currently evaluating VerneMQ and would need this feature in the Helm chart. It seems like a very small change. Can I do anything to speed up the process to get this merged? It seems like a very reasonable and small change.

**Comment by Chadys** [comment]
Any news on this? @ioolkos ? Is there anything left to do before this can be merged?

**Comment by ioolkos** [comment]
@Chadys the imagePullSecret is used to pull a Docker image from a private repository, right?
Would that still be the official VerneMQ Docker image, or would it serve as a way to use your own Docker images?

While I'm inclined to merge this, please note that it seems no one wanting this feature merged here supports the VerneMQ project in any form or fashion...

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
resolved via https://github.com/vernemq/docker-vernemq/pull/384

**Pull request closed without merging**
