### PR TITLE
Add automatic discovery for Docker Swarm

### PR DESCRIPTION
**Pull request by Victor-Savu**
Hi! I love that vernemq is so great with clustering and so Docker-friendly. I predominantly use Docker Swarm as an orchestration framework so I made vernemq scale automatically in Swarm the way it does in Kubernetes.

All that is needed are three environment variables:
```Dockerfile
environment:
    DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
    SERVICE_NAME: "{{.Service.Name}}"
    SERVICE_LABELS: "{{.Service.Labels}}"
    DOCKER_VERNEMQ_DISCOVERY_SWARM: 1
```
Please let me know if you find this useful and if there is a chance you would accept my contribution, I would need some guidance with updating the documentation.

Thanks!

### CODE REVIEW

**Comment by dergraf** [comment]
Hello @Victor-Savu 
please excuse that nobody has replied to your PR. In any case thank you for your contribution.
Could you check the current start script and see if your PR is still required. If you think it is still required please do a quick rebase so I can have a closer look at it asap. Again, very sorry for the delay!

**Comment by Victor-Savu** [comment]
Hi @dergraf ! I'm sorry, but I am having a few very busy weeks. I will do a rebase as soon as I get a chance. The current start script does not do automatic docker swarm discovery or healing as far as I can tell.

**Comment by Victor-Savu** [comment]
OK, I fixed the merge conflicts and I have to say I am really ashamed that it too me so much. The conflict mainly stemmed from the rename `/etc/vernemq` -> `/vernemq/etc`. Sorry it took so long!

**Comment by dergraf** [comment]
Hello @Victor-Savu 

thanks again for your patience and contribution, and please excuse for rejecting the PR. But, thanks to your PR I learned several things about Docker Swarm, so it definitely influenced my work in #145 .

Nevertheless I wanted to give you a feedback on your PR.

With your PR every replica starts an extra background process for reconciling cluster state, e.g. figuring out the difference between what is in the DNS and the VerneMQ cluster state. IMO cluster wide reconciliation should be done by a specific service (like a Kubernetes operator) instead of every replica. Therefore I'd preferred a way where every replica is only responsible for itself, e.g. once joined no more work needs to be done. Thanks to your PR I learned more about Docker Swarm and figured out that my preferred behaviour isn't straightforward to implement (because of lacking statefulset abstraction). For this reason I came up with the current approach which relies on a specific discovery service. I know it's a compromise, but I think it's good enough until we have a better discovery facility built directly into VerneMQ.

**Pull request closed without merging**
